// scripts/build-skill-bodies.ts
//
// Reads the four platform-skill markdown files and emits
// src/lib/platform-skills/bodies.ts as a const map. Run after
// editing any .md file in that directory:
//
//   npx tsx scripts/build-skill-bodies.ts
//
// Why: Next.js / Vercel doesn't ship .md files into the serverless
// bundle unless they're imported as code. Inlining as a string map
// guarantees the runtime can always read them.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const skillsDir = join(root, 'src/lib/platform-skills');

const FILES: Record<string, string> = {
  linkedin: 'linkedin-post.md',
  newsletter: 'newsletter-issue.md',
  blog: 'blog-post.md',
  note: 'note.md',
};

function tsTemplateLiteral(body: string): string {
  return (
    '`' +
    body
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${') +
    '`'
  );
}

const today = new Date().toISOString().slice(0, 10);
let out = `// AUTO-GENERATED by scripts/build-skill-bodies.ts on ${today}.\n`;
out += `// Edit the .md files in src/lib/platform-skills/ then re-run:\n`;
out += `//   npx tsx scripts/build-skill-bodies.ts\n\n`;
out += `import 'server-only';\n`;
out += `import type { Platform } from '@/app/studio/page/usePlatform';\n\n`;
out += `export const PLATFORM_SKILL_BODIES: Record<Platform, string> = {\n`;
for (const [name, fname] of Object.entries(FILES)) {
  const body = readFileSync(join(skillsDir, fname), 'utf-8');
  out += `  ${name}: ${tsTemplateLiteral(body)},\n`;
}
out += `};\n`;

writeFileSync(join(skillsDir, 'bodies.ts'), out);
console.log(`Wrote ${skillsDir}/bodies.ts (${out.length} chars).`);
