// AUTO-GENERATED by Phase 23 v2 slice 8 fix on 2026-05-07.
// Inlined platform-skill markdown so Vercel ships the strings
// in the bundle (readFileSync at /var/task didn't ship the .md
// files). To edit the craft text, edit the .md files in this
// directory and regenerate this file via scripts/build-skill-bodies.ts.

import 'server-only';
import type { Platform } from '@/app/studio/page/usePlatform';

export const PLATFORM_SKILL_BODIES: Record<Platform, string> = {
  linkedin: `# LinkedIn post — writing strategy

## Shape

A LinkedIn post that earns the click is built like a TV cold-open. First two lines must do all the work, because they're the only thing the reader sees in feed. The "...see more" cuts after roughly 210 characters on desktop, fewer on mobile.

## Hook patterns that land

Five shapes consistently outperform on LinkedIn for the kind of writing Payton does:

1. **Mundane Moment + Revelation** — "I spent 15 years writing sermons before I ever wrote a subject line. Turns out, they're the same job." Personal-specific opening, then a contrast that reframes.
2. **Bold Claim + Proof Tease** — "Most founders' homepages are killing their conversion. Here's what's actually working." Claim that creates friction, then promise of evidence.
3. **Question That Names a Tension** — "What if everything you know about marketing is wrong?" Works only when the post actually delivers the answer; cheap-shot questions tank.
4. **Specific Number + Counter-Intuitive Insight** — "I A/B tested 47 subject lines. The 3-word ones won." Quantification grants credibility; counter-intuitive insight earns the read.
5. **Story Setup + Stakes** — "Last week I almost missed my flight because I was crying in an airport bookstore. Here's what I learned about B2B copy." Personal stakes, then a turn into the post's actual subject.

## Length

180-240 words is the sweet spot. Shorter than 100 reads as thin; longer than 300 starts losing readers around line 8. Aim for ~180 unless the post genuinely needs the room.

## Line break rhythm

Single sentences. Each line break creates a beat. White space carries the eye. Reader on mobile sees one sentence at a time as they scroll; rhythm matters more than punctuation.

## What to avoid

- Three-item lists at the start ("X, Y, and Z"). Reads as AI.
- "Here's the thing" / "Hot take" / "Unpopular opinion" — burned phrases.
- Vague second-person ("As leaders, we…"). Specific or first-person only.
- Em dashes used as "but actually" pivots. Comma + period is stronger.
- Closing question that asks the reader to comment. The post should earn the comment, not beg for it.

## Closer patterns

- **Through-line restatement** — one sentence that lands the post's argument with no new information.
- **Sharp single sentence** — sometimes a 7-word period is the whole closer.
- **Concrete next move** — "Try this on your next post" works only when the post taught something specific.

## Voice notes for Payton (Christian Story Lab)

The audience is Christian creators / writers / founders. Story-shaped framing lands. Sermon-craft references resonate (most readers came up through some version of pulpit or stage). Avoid "ministry" as the word that frames the work; "story" / "craft" / "stretch" carry more weight without flattening the audience to one tribe.
`,
  newsletter: `# Newsletter issue — writing strategy

## Shape

Newsletter issues for Christian Story Lab follow a Lede + 3-5 Sections + Closer arc. Target ~1000 words. The lede is its own paragraph — sometimes a single sentence — that hooks the reader and frames the question the issue answers.

## Lede patterns

The lede is the most important paragraph. Three patterns consistently land:

1. **Specific scene + named tension** — "I was on the phone with Arlo when Jalen Williams walked out at MSG." Concrete moment that the rest of the issue interrogates.
2. **Question reframed** — "Most writers think the hard part is finding ideas. The hard part is staying with them." Sets up the reframe the issue then earns.
3. **Counter-narrative** — "Everyone's writing about X. Here's what they're missing." Works when the issue actually delivers the missing thing.

## Section discipline

Each section earns its existence by carrying ONE point. Three to five sections, each ~150-250 words. Sections without a clear point become filler and the reader can feel it.

H2 per section. The H2 is not a clever line; it's a clear claim. ("Sermon-craft is the same as subject-line craft" is a section header. "The Hidden Truth Most Writers Miss" is not.)

## Voice cadence

- Sentences vary in length. A long observation followed by a short period creates beat. Three medium sentences in a row sound robotic.
- Specifics over abstractions. "47 subject lines" beats "many subject lines."
- Personal stakes named, not assumed. The reader didn't have your week.
- Active voice. "The team built X" beats "X was built by the team."

## Story-frame strategies

Christian Story Lab's wedge is treating story-craft seriously. That means:

- Open in scene where possible.
- Name the tension before the resolution.
- Withhold the answer until the reader has felt the question.
- Closers should land the through-line in a sentence the reader will remember tomorrow.

## What to avoid

- Em dashes used as "but actually" pivots. They flag AI writing in this audience.
- "It's not just X — it's Y" antithesis flips. Cut.
- Three-item lists of abstract qualities ("bold, faithful, urgent"). Cut.
- Vague second-person plural ("As we navigate the modern landscape…"). Replace with first-person specific.
- "Crucial," "vital," "pivotal," "delve," "tapestry," "underscore." All burned.
- Closing with "What do you think? Reply and let me know." Reader replies because the issue earned a reply, not because it asked.

## Closer patterns

- **Specific next step** — one concrete thing the reader can try this week.
- **Through-line restatement** — the issue's argument in a sentence.
- **Question the reader has to sit with** — only if the issue genuinely earns the question.
- **Personal commitment** — what the writer is doing about the thing they just argued. Risky but lands when sincere.

## Length notes

900-1100 words is the target band. Below 800 and the issue feels thin; above 1300 and engagement drops. CSL's best-performing issues sit around 1050.
`,
  blog: `# Blog post — writing strategy

## Shape

A blog post is the longer-form sibling of the newsletter issue. Target ~700 words for sharp pieces, up to ~1500 for the deeper arcs. Body reads as editorial — wider column, serif-leaning, bigger headings.

## Opening

Blog posts tolerate slower openings than LinkedIn or newsletter issues. The reader who clicked your blog has already chosen to spend 5 minutes. Don't waste that, but don't burn the lede with a twist that needs a 200-word setup either.

Three patterns:

1. **Scene + question** — open in a specific moment, then ask the question the post answers.
2. **Counter-claim** — "The conventional wisdom about X is wrong." Earned only if the post actually shows it.
3. **Personal context** — "I've spent the last six months thinking about X. Here's where I've landed." Works when the writer's authority is established or being earned in the post itself.

## Section discipline

Each section ~200-400 words. H2 per section. Subsections (H3) only when the argument genuinely splits.

The blog body has more room for examples + parentheticals + quoted passages than the newsletter. Use the room — but every paragraph should still serve the through-line.

## Voice notes

- Slightly more formal than newsletter, slightly less than long-form essay.
- Specifics still beat abstractions.
- Active voice unless the actor genuinely doesn't matter.
- Embedded quotes from the user's own archive land well — drop a line from a past piece, link to it.

## What to avoid

Same banned-word list as newsletter (em-dash pivots, antithesis flips, "crucial," "vital," "delve," "tapestry," "underscore," "showcase"). Plus:

- Long preambles before the actual point.
- Bullet lists of three abstract qualities. Bullets are for genuinely-list-shaped content.
- Closing with a "What about you?" question that the post didn't earn.

## Closer

A blog post can take a longer closer than a LinkedIn post or a newsletter — sometimes a whole paragraph. But the final sentence should still land the post's argument in a way the reader will remember.

## Length notes

700 words for sharp argumentative pieces. 1200-1500 for deeper essays where the reader signed up for a longer ride. Above 2000 and you should ask whether this is a blog post or two.
`,
  note: `# Note — writing strategy

## Shape

Note mode is the freeform writing surface. No platform shape, no word target, no specific arc to land. Use it for journal entries, drafts that haven't found a platform yet, or quick captures that might become something later.

## What Thoughtbed should do in Note mode

The companion stays present but quieter:

- Surface Garden ideas the same way it does for other platforms.
- Don't push toward a hook / closer / word target.
- Don't suggest "publishing" the note — it's not a publishable shape.
- If the user starts shaping the note toward a specific platform (length picks up, structure emerges, hooks form), the companion can ask: "This is starting to read like a LinkedIn post. Want to switch the frame?"

## Voice

The same anti-AI rules apply. No em-dash pivots, no antithesis flips, no banned words. The note can be loose, but it shouldn't read like a machine.
`,
};
